/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCampusHeroRouteImport } from './routes/api/campus-hero'
import { Route as ApiCampusRouteImport } from './routes/api/campus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampusHeroRoute = ApiCampusHeroRouteImport.update({
  id: '/api/campus-hero',
  path: '/api/campus-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampusRoute = ApiCampusRouteImport.update({
  id: '/api/campus',
  path: '/api/campus',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/campus': typeof ApiCampusRoute
  '/api/campus-hero': typeof ApiCampusHeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/campus': typeof ApiCampusRoute
  '/api/campus-hero': typeof ApiCampusHeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/campus': typeof ApiCampusRoute
  '/api/campus-hero': typeof ApiCampusHeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/campus' | '/api/campus-hero'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/campus' | '/api/campus-hero'
  id: '__root__' | '/' | '/api/campus' | '/api/campus-hero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCampusRoute: typeof ApiCampusRoute
  ApiCampusHeroRoute: typeof ApiCampusHeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campus-hero': {
      id: '/api/campus-hero'
      path: '/api/campus-hero'
      fullPath: '/api/campus-hero'
      preLoaderRoute: typeof ApiCampusHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campus': {
      id: '/api/campus'
      path: '/api/campus'
      fullPath: '/api/campus'
      preLoaderRoute: typeof ApiCampusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCampusRoute: ApiCampusRoute,
  ApiCampusHeroRoute: ApiCampusHeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
